name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Install Python dependencies
        run: |
          python3 -m pip install poetry==1.1.11
          python3 -m poetry install
      - name: Test with pytest
        run: |
          python -m poetry run python -m pytest -sxv